// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycidplxlgxprmjshldau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljaWRwbHhsZ3hwcm1qc2hsZGF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNTE3NDMsImV4cCI6MjA2NzkyNzc0M30.ReBIGPt_-muVTv7MrFPmyxbcF2QEH4BqVZa_V09rp0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});